name: Deploy Vanilla JavaScript PWA Checklist App
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Build Project (if any build step exists)
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
